package com.xxx.grad.entity;

import lombok.*;

/**
 * this class code is automatically generated by the tool "Table2Entity";
 * the tool is for fast generating entity according to Database table;
 * 
 * the purpose of the tool is to better help my girlfriend to faster finish her graduation design;
 * 
 * @Author: Simin Wang
 * @Tool_Created_Date: 4/29/2021 2:56 AM
 * @Code_Generated_Date: 5/1/21 5:45 PM 
 */

@Data
public class Contact { 

    @NonNull
    private Long id;

    @NonNull
    private String name;

    private Long telephone;

    private String email;

    private String remarks;

    private String notes;

    private String url;

    private String other;

    private Long userid;

    public Contact(@NonNull Long id, @NonNull String name, Long telephone, String email, String remarks, String notes, String url, String other, Long userid) {
        this.id = id;
        this.name = name;
        this.telephone = telephone;
        this.email = email;
        this.remarks = remarks;
        this.notes = notes;
        this.url = url;
        this.other = other;
        this.userid = userid;
    }
}