package com.xxx.grad.entity;

import lombok.*;

/**
 * this class code is automatically generated by the tool "Table2Entity";
 * the tool is for fast generating entity according to Database table;
 * 
 * the purpose of the tool is to better help my girlfriend to faster finish her graduation design;
 * 
 * @Author: Simin Wang
 * @Tool_Created_Date: 4/29/2021 2:56 AM
 * @Code_Generated_Date: 5/1/21 4:14 AM 
 */

@Data
public class Session { 

    @NonNull
    private Long userid;

    private Long logoutdate;

    private Long logindate;

    private String token;

    public Session(@NonNull Long userid, Long logoutdate, Long logindate, String token) {
        this.userid = userid;
        this.logoutdate = logoutdate;
        this.logindate = logindate;
        this.token = token;
    }
}