package com.xxx.grad.entity;

import lombok.*;

/**
 * this class code is automatically generated by the tool "Table2Entity";
 * the tool is for fast generating entity according to Database table;
 * 
 * the purpose of the tool is to better help my girlfriend to faster finish her graduation design;
 * 
 * @Author: Simin Wang
 * @Tool_Created_Date: 4/29/2021 2:56 AM
 * @Code_Generated_Date: 4/25/21 10:22 AM 
 */

@Data
public class Transaction { 

    @NonNull
    private Long id;

    private String common;

    private Long createdate;

    private String body;

    private Integer isfinished;

    private Long owner;

    private Long finishdate;

    private String other;

    public Transaction(@NonNull Long id, String common, Long createdate, String body, Integer isfinished, Long owner, Long finishdate, String other) {
        this.id = id;
        this.common = common;
        this.createdate = createdate;
        this.body = body;
        this.isfinished = isfinished;
        this.owner = owner;
        this.finishdate = finishdate;
        this.other = other;
    }
}