package com.xxx.grad.entity;

import lombok.*;

/**
 * this class code is automatically generated by the tool "Table2Entity";
 * the tool is for fast generating entity according to Database table;
 * 
 * the purpose of the tool is to better help my girlfriend to faster finish her graduation design;
 * 
 * @Author: Simin Wang
 * @Tool_Created_Date: 4/29/2021 2:56 AM
 * @Code_Generated_Date: 4/25/21 10:22 AM 
 */

@Data
public class User { 

    @NonNull
    private Long id;

    @NonNull
    private String name;

    private Integer age;

    private String email;

    public User(@NonNull Long id, @NonNull String name, Integer age, String email, Long registerdate, String other, Long phone, String password) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.email = email;
        this.registerdate = registerdate;
        this.other = other;
        this.phone = phone;
        this.password = password;
    }

    private Long registerdate;

    private String other;

    private Long phone;

    private String password;


}