spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.157.2:3306/grad
    username: admin
    password: admin

  server:
    port: 8080



#  thymeleaf:
#    prefix: classpath:/templates/
#    cache: false
#    content-type: text/html
#    mode: HTML5

  resources:
    static-locations: classpath:/

  mvc:
    view:
      prefix: /view/
      suffix: .jsp

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true


server:
  tomcat:
    uri-encoding: UTF-8
